### ISSUE TITLE
Add an argument for watching arbitrary folders

### ISSUE THREAD

**Issue by kmike** [GaretJax/sphinx-autobuild#1]
Currently it seems to watch doc source dir and doc output dir, but if autodoc extension is enabled watching python source code is also needed.

**Comment by ajylee** [comment]
I've rebased GaretJax's "1-arbitrary-watch" to v0.4.0.
Please see:
https://github.com/GaretJax/sphinx-autobuild/tree/feature/1-arbitrary-watch-0.4.0
I am also using it currently and it works fine.

@GaretJax 
Can you please update your "1-arbitrary-watch" branch to my "1-arbitrary-watch-0.4.0"? I just extracted the feature as a patch and applied it to v0.4.0.

**Comment by GaretJax** [comment]
Fixed in #22
