### ISSUE TITLE
Global file name ignore

### ISSUE THREAD

**Issue by montefra** [GaretJax/sphinx-autobuild#24]
I've just discovered your package and I seems very nice.

My setup:
* python 3.4
* Sphinx v1.2.3
* sphinx-autobuild v0.5
* vim as editor

As I'm using `autodoc`, I also want to follow the code directory, so I've added the option `-z "../mylib"`. This is easy.

But the autobuild fires every time I edit a file, e.g. `doc.rst`, as vim modifies `.doc.rst.swp` file, but does nothing as the file has not been saved. Then when I save it both the `doc.rst` `.doc.rst.un~` are changed and the autobuilds runs for both files. To avoid this I've added

    -i 'source/.??*' -i 'source/*~'

to the command line. If I modify one of the python files in `mylib`, e.g. `mylib/module.py`, the situation is even worse. The build fires as I type because of `mylib/.module.py.swp` and, when I save the file, the build needlessly fires a lot of times, mostly because the files in `libvhc/__pycache__` are modified when sphinx runs.

I can avoid it with

     -i '../mylib/__pycache__/*' -i '../mylib/.??*' -i '../mylib/*~'

If I add any subdirectory in `mylib` I'll need to repeat the above line.

For a big project with subpackages and subdirectories in `source` this gets extremely hard to maintain.

Would it be possible to define the ignore option like

    -i '.??*' -i '*~' -i '__pycache__'

such that any file or directory matching the give names is ignored, without to specify in which directory do they live?

**Comment by GaretJax** [comment]
@montefra, could you please check if https://github.com/GaretJax/sphinx-autobuild/pull/26 solves your issue?

**Comment by montefra** [comment]
Now I'm on holiday until next Tuesday. I'll try to remember to do it as soon as possible. If I don't come back within one week, please ping me.

**Comment by GaretJax** [comment]
Don't worry, in the end it took me almost a month to answer.

**Comment by GaretJax** [comment]
Ping @montefra ;-)

**Comment by montefra** [comment]
I'm just about to give a try. I hope to have an answer in few hours

**Comment by montefra** [comment]
It works! Thank you.

    -r '\.\S+?swp' -r '__pycache__' -r '\S+?~'

avoids to build if anything like ``.*swp``, ``*~`` and ``*__pycache__*`` is modified.
When do you plan to push this into pypi.

**Comment by GaretJax** [comment]
Cool! I'll add __pycache__ to the default ignores. Also, will probably release already today.

**Comment by GaretJax** [comment]
@montefra I just released 0.5.1

**Comment by GaretJax** [comment]
Just wait with updating, I introduced a bug... shall have waited for tests to pass, shame on me. Give me 5 minutes

**Comment by GaretJax** [comment]
Ok, 0.5.2 is fine, enjoy!

**Comment by montefra** [comment]
great. Thanks for the effort. 
Excluding pycache by default is a good idea +1. I'll update next week.
