### ISSUE TITLE
favicon.ico issue

### ISSUE THREAD

**Issue by orotau** [GaretJax/sphinx-autobuild#30]
Ubuntu 14.04
Virtual environment using Python 3.4
Sphinx 1.3.1
sphinx-autobuild==0.5.2
`sphinx-quickstart -q --project="Soul Documentation" --author="Graham" -v 0.1 --no-makefile --no-batchfile`
`sphinx-autobuild . _build_html`

When I access 127.0.0.1:8000
this appears on the terminal
`[I 150501 18:11:06 web:1825] 200 GET / (127.0.0.1) 13.79ms`
`[E 150501 18:11:06 web:1421] Uncaught exception GET /favicon.ico/ (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/favicon.ico/', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:37.0) Gecko/20100101 Firefox/37.0', 'Cookie': 'csrftoken=6WK34XkzyOsDqu7Lc2BEvFw5LDOHGQGz; mezzanine-device=mobile; mezzanine-comment-url=; mezzanine-comment-name=admin; mezzanine-comment-email="example@example.com"; mezzanine-rating="\\054blog.blogpost.1"', 'Connection': 'keep-alive', 'Accept-Encoding': 'gzip, deflate', 'Host': '127.0.0.1:8000', 'Accept-Language': 'en-US,en;q=0.5', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'})
    Traceback (most recent call last):
      File "/home/graham/Virtual-Environments/py34_dj177/lib/python3.4/site-packages/tornado/web.py", line 1346, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/graham/Virtual-Environments/py34_dj177/lib/python3.4/site-packages/livereload/handlers.py", line 177, in get
        return self.create_index(rootdir)
      File "/home/graham/Virtual-Environments/py34_dj177/lib/python3.4/site-packages/livereload/handlers.py", line 213, in create_index
        files = os.listdir(root)
    FileNotFoundError: [Errno 2] No such file or directory: '/home/graham/Dropbox/mp_soul_whero/docs/_build_html/favicon.ico/'`
`[E 150501 18:11:06 web:1825] 500 GET /favicon.ico/ (127.0.0.1) 52.08ms`

The workaround for me is to uncomment the line in conf.py

``` python
#html_favicon = None
```

**Comment by pradyunsg** [comment]
I can't reproduce this with the current version of Sphinx, and the Sphinx version seems to be really old here.

Gonna say that this got fixed upstream at some point.
