### ISSUE TITLE
Support watching file list & patterns

### ISSUE THREAD

**Issue by nfarrar** [GaretJax/sphinx-autobuild#35]
While [python-livereload](https://github.com/lepture/python-livereload) will take a list of files or pattern (i.e. `PROJECT_ROOT/*.rst`), it looks like sphinx-autobuild will only allow you to specify an extra path. I was specifically trying to use this to rebuild my docs when it sees an rst file in the root directory change (they are included in the docs) - globs wouldn't work and passing in the root directory causes recursive reloads (it reloads everytime docs/_build is regenerated).

Any chance it'd be possible to add supports for patterns?

**Comment by GaretJax** [comment]
@nfarrar you can use the `-r`/`--re-ignore` option to specify one or more regexes for paths to be ignored. My guess is that `-r _build/.*` should work.

See here for the implementation:
* https://github.com/GaretJax/sphinx-autobuild/blob/develop/sphinx_autobuild/__init__.py#L31-L34
* https://github.com/GaretJax/sphinx-autobuild/blob/develop/sphinx_autobuild/__init__.py#L222
* https://github.com/GaretJax/sphinx-autobuild/blob/develop/sphinx_autobuild/__init__.py#L141-L143
