### ISSUE TITLE
Watching other directories

### ISSUE THREAD

**Issue by Startouf** [GaretJax/sphinx-autobuild#48]
I'm not sure more an issue or a feature request, but given the following directory structure

```
-- benchmark/
-- -- summary.rst
-- doc/
-- -- sphinx/
-- -- -- conf.py
-- -- -- index.rst
-- -- -- _build/ 
```

One on the main document files in `doc/sphinx/` require a file located outside the main doc directory `.. include:: ../../benchmark/report.rst`

That file `../../benchmark/report.rst` is not being watched. Would it be possible to specify additional directory to watch ? Or maybe we could specify a top-level directory to watch instead of the same directory as the source ?

**Comment by GaretJax** [comment]
Hi @Startouf, if I understand correctly, what you're asking is already implemented. See the `-z` flag: https://github.com/GaretJax/sphinx-autobuild/blob/develop/sphinx_autobuild/__init__.py#L240

**Comment by Startouf** [comment]
Oh waoh, that was even in the main readme... sorry about that.
