### ISSUE TITLE
Hidden docs\.venv folder in pypi tar

### ISSUE THREAD

**Issue by chohner** [GaretJax/sphinx-autobuild#56]
In the newest pypi .tar download for 0.7.0 (https://pypi.python.org/pypi/sphinx-autobuild/0.7.0), there is a hidden `docs\.venv` folder. It makes the .tar file size explodes to 11mb (final folder size is 33mb) and wasn't there in `0.6.0`.

Probably should be removed.

**Comment by GaretJax** [comment]
Probably...

Thanks for catching that @chohner, shame on me :smile: 

This should not happen anymore in the future: https://github.com/GaretJax/sphinx-autobuild/commit/f3c3c51287706152745fe6e259f6ce347647cfe2

Also, 0.7.1 released.
