### ISSUE TITLE
Can't reach server running inside Docker container

### ISSUE THREAD

**Issue by ggalmazor** [GaretJax/sphinx-autobuild#68]
Hi! I'm wrapping my sphinx dev environment inside a Docker container to make it portable and easier to use for other users and I'm interested on adding sphinx-autobuild into it.

Up to now, I was able to run a `python -m http.server` inside the container and access it from my host machine, no problem.

I've made some tries with sphinx-autobuild and the building part works great but I can't access the web server, even though I've EXPOSEd the port I'm using in my Dockerfile and I'm binding a host port to it, as with the `http.server` module.

It seems that the server the sphinx-autobuild module is starting isn't getting my hosts requests.

Any idea on how to run it on debug mode, or have some logs to look further into this issue?

**Comment by iicky** [comment]
@ggalmazor 

I ran into this same issue - the trick for me was to change the host from `127.0.0.1` to `0.0.0.0`. Here is my CMD in my `Dockerfile` (I am running on port 8181):

```
CMD ["sphinx-autobuild", "--host", "0.0.0.0", "--port", "8181", "docs/source", "docs/build"]
```

**Comment by ggalmazor** [comment]
Thanks, @iicky!

Honestly, I had solved the issue somehow. I'll review what I did and leave feedback here :)
(might as well be just what you've commented)

**Comment by iicky** [comment]
@ggalmazor Awesome, keep me posted - definitely excited about having this tool!

**Comment by ggalmazor** [comment]
I guess we can close the issue now :)

**Comment by ryanewtaylor** [comment]
@ggalmazor I have the same problem and while `--host 0.0.0.0` solves it, the page no longer auto-refreshes when rebuilt. I am using a Windows host and Windows docker container. I don't see a `--poll` option as you have listed. Did auto-refreshing work for you?
