### ISSUE TITLE
Optional argument to run script / bash cmd on rebuild event

### ISSUE THREAD

**Issue by HarisGodil** [GaretJax/sphinx-autobuild#69]
My use case:
I have a script which I currently run before sphinx-build that automatically places automodule directives in the relevant files, so that my test documentation will pull in the appropriate docstrings.

Having the ability to add `--run ./link_tests` would allow me to keep all the functionality I'm currently getting in my workflow of manually rebuilding

I'm planning on working on this (at some point next week), but I'm still posting this as an issue just incase anyone has an objection to this functionality or has some feedback / additional functionality wants.

**Comment by pradyunsg** [comment]
Sounds like a reasonable request!
