### ISSUE TITLE
python script using livereload-python

### ISSUE THREAD

**Issue by ngzhian** [GaretJax/sphinx-autobuild#80]
Thanks for this project! It makes my workflow really smooth.
I found some issues with spurious building and reloads, it looked like it was maybe too eagerly watching changes to files.
I looked up the livereload-python package (used by this), and found that they have a simple [script](https://github.com/lepture/python-livereload#script-example-sphinx):

```
#!/usr/bin/env python
from livereload import Server, shell
server = Server()
server.watch('docs/*.rst', shell('make html', cwd='docs'))
server.serve(root='docs/_build/html')
```

Leaving this here in case anyone faces similar issues

**Comment by pradyunsg** [comment]
Thanks for sharing this. :)
